<link rel="stylesheet" href="css/style.footer.css">

    <footer>
        <section>
            <h2>Navegación</h2>
            <ul>
                <a href="home" class="links"><li>Inicio</li></a> 
                <a href="noticia" class="links"><li>Ultima Noticia</li></a>
            </ul>
        </section>
        <section>
            <h2>Categorias</h2>
            <ul>
                <li>Anime</li>
                <li>Manga</li>
                <li>Peliculas</li>
                <li>Videojuegos</li>
            </ul>
        </section>
        <section>
            <h2>Cuenta</h2>
            <ul>
                <li><a href="login" class="links">Iniciar sesión</a></li>
                <li><a href="logout" class="links">Cerrar sesión</a></li>
            </ul>
        </section>
    </footer>
