<!--Header-->

<?php 
  require './templates/header.phtml';
?>

<!--Login-->
<div class="login-body">
  <div class="login-box">
    <div>
      <h1>Iniciar Sesión</h1>
        <form method="POST" action="auth">
          <div class="datos-box">
            <label for="nombre">Usuario</label>
            <input type="text" name="nombre" id="nombre" required>
          </div>
          <div class="datos-box">
          <label for="contrasena">Contraseña</label>
          <input type="password" name="contrasena" id="contrasena" required>
          </div>
          <div class="datos-box">
          <input type="submit" name="login" value="Iniciar Sesión" id="login">
          </div>
        </form>
    </div>
  </div>
</div>

<!--Footer-->

<?php 
  require './templates/footer.phtml';
?>