<!--Header-->

<?php 
  require './templates/header.phtml';
?>

<!--Categorias-->
<div class="cuerpo">
<ul class="main-categorias">
  <li>Anime</li>
  <li>Manga</li>
  <li>Peliculas</li>
  <li>Videojuegos</li>
</ul>

<!--Main body-->

<?php foreach($noticias as $noticia):?>

<div class="main-noticias">
  <div class="noticia-titulo">
    <div class="container-img"> 
      <a href="view-noticia" class="link">
        <img class="noticia-img" src="<?=$noticia->Foto?>" alt="">
      </a>
    </div>
      <a href="view/noticia/<?= $noticia->IDNoticia?>" class="link">
        <?= $noticia->Titulo?>
      </a>
  </div>
  <div class="botones">
    <button>Editar noticia</button>
    <button>Eliminar noticia</button>
  </div>
</div>

<?php endforeach?>

  <div class="button-add-noticia">
    <button>Añadir noticia</button>
  </div>
</div>

<!--Footer-->

<?php 
  require './templates/footer.phtml';
?>